"""Tests for research brief export — Phase 4 Track B.

Covers: Markdown string assembly, JSON export shape.
"""
import json

import pytest

from app.schemas.research import Argument, ResearchBrief


def _sample_brief() -> ResearchBrief:
    return ResearchBrief(
        topic="Machine Learning in Healthcare",
        executive_summary="ML shows promising results in diagnostic imaging.",
        key_arguments=[
            Argument(
                claim="CNN-based models achieve 95% accuracy in X-ray classification",
                evidence_chunk_ids=["chunk_001", "chunk_002"],
                stance="supporting",
            ),
        ],
        evidence_table=[
            {
                "chunk_id": "chunk_001",
                "document_title": "Radiology AI Review 2025",
                "key_point": "Deep learning outperforms radiologists in specific tasks",
            },
        ],
        counterarguments=[
            Argument(
                claim="Models may encode racial bias from training data",
                evidence_chunk_ids=["chunk_003"],
                stance="opposing",
            ),
        ],
        knowledge_gaps=["Lack of studies in low-resource settings"],
        recommended_reading=[
            {"document_title": "AI in Medicine Survey", "reason": "Comprehensive overview"},
        ],
        confidence=0.8,
    )


class TestMarkdownExport:
    """Verify Markdown export string assembly."""

    def _to_markdown(self, brief: ResearchBrief) -> str:
        """Simplified MD assembly matching what the export endpoint would produce."""
        lines = [
            f"# Research Brief: {brief.topic}",
            "",
            "## Executive Summary",
            brief.executive_summary,
            "",
            "## Key Arguments",
        ]
        for arg in brief.key_arguments:
            lines.append(f"- **{arg.stance.title()}**: {arg.claim}")
            if arg.evidence_chunk_ids:
                lines.append(f"  - Sources: {', '.join(arg.evidence_chunk_ids)}")
        lines.append("")
        lines.append("## Counterarguments")
        for arg in brief.counterarguments:
            lines.append(f"- **{arg.stance.title()}**: {arg.claim}")
        lines.append("")
        lines.append("## Knowledge Gaps")
        for gap in brief.knowledge_gaps:
            lines.append(f"- {gap}")
        lines.append("")
        lines.append(f"*Confidence: {brief.confidence:.0%}*")
        lines.append("")
        lines.append("---")
        lines.append("*Generated by NexusMind*")
        return "\n".join(lines)

    def test_contains_topic_heading(self):
        md = self._to_markdown(_sample_brief())
        assert "# Research Brief: Machine Learning in Healthcare" in md

    def test_contains_executive_summary(self):
        md = self._to_markdown(_sample_brief())
        assert "ML shows promising results" in md

    def test_contains_arguments(self):
        md = self._to_markdown(_sample_brief())
        assert "CNN-based models" in md
        assert "Supporting" in md

    def test_contains_counterarguments(self):
        md = self._to_markdown(_sample_brief())
        assert "racial bias" in md

    def test_contains_knowledge_gaps(self):
        md = self._to_markdown(_sample_brief())
        assert "low-resource settings" in md

    def test_contains_confidence(self):
        md = self._to_markdown(_sample_brief())
        assert "80%" in md

    def test_contains_footer(self):
        md = self._to_markdown(_sample_brief())
        assert "NexusMind" in md


class TestJsonExport:
    """Verify JSON export shape."""

    def test_roundtrip_via_model_dump(self):
        brief = _sample_brief()
        data = brief.model_dump()
        restored = ResearchBrief.model_validate(data)
        assert restored.topic == brief.topic
        assert restored.confidence == brief.confidence
        assert len(restored.key_arguments) == len(brief.key_arguments)

    def test_json_serializable(self):
        brief = _sample_brief()
        text = json.dumps(brief.model_dump())
        assert '"topic"' in text
        assert '"confidence"' in text
